
title: 爱情海笔记
email: xiahaifeng2000@gmail.com
description: > 
  hai的学习笔记

baseurl:
url: https://love-hai.github.io

permalink: /:year-:month/:title
timezone:

favicon: /assets/img/favicon.ico

google_analytics: #UA—XXXXXXXX-X
disqus_shortname: #disqus shortname
cusdis:
    app_id: #your cusdis app_id

user:
  name: lovehai
  pic: /assets/img/love_hai_main.jpg
  picAlt: "catbook"
  job: 学习使我不劳累
  aboutme: true # comment this out if you don't need the 'about' page.

exclude:
  - README.md
  - LICENSE
  - github

defaults:
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      comment: true   
      toc: true

markdown_ext: "markdown,mkdown,mkdn,mkd,md"
markdown: kramdown 

# Filtering Content
show_drafts: null
limit_posts: 0
future:      false
unpublished: false
